using Unity.MLAgents;
using Unity.MLAgents.Sensors;
using Unity.MLAgents.Actuators;
using UnityEngine;

/// <summary>
/// ML-Agents를 이용한 테트리스 학습 에이전트
/// TetrisAgentAPI.md 기반으로 구현
/// </summary>
public class TetrisAgent : Agent
{
    [Header("환경 연결")]
        public TetrisBoard board;

            /// <summary>
                /// 에피소드 시작 시 호출 - 보드 초기화
                    /// </summary>
                        public override void OnEpisodeBegin()
                            {
                                    board.ResetBoard();
                                        }

                                            /// <summary>
                                                /// 관찰값 수집 - 보드 상태를 AI에게 전달
                                                    /// </summary>
                                                        public override void CollectObservations(VectorSensor sensor)
                                                            {
                                                                    // 보드 그리드 상태 (10 x 20 = 200개)
                                                                            int[,] grid = board.GetGrid();
                                                                                    for (int y = 0; y < 20; y++)
                                                                                            {
                                                                                                        for (int x = 0; x < 10; x++)
                                                                                                                    {
                                                                                                                                    sensor.AddObservation(grid[x, y] > 0 ? 1f : 0f);
                                                                                                                                                }
                                                                                                                                                        }

                                                                                                                                                                // 현재 피스 위치
                                                                                                                                                                        Vector2Int piecePos = board.GetCurrentPiecePosition();
                                                                                                                                                                                sensor.AddObservation(piecePos.x / 10f);
                                                                                                                                                                                        sensor.AddObservation(piecePos.y / 20f);

                                                                                                                                                                                                // 현재 피스 타입
                                                                                                                                                                                                        sensor.AddObservation(board.GetCurrentPieceType());

                                                                                                                                                                                                                // 다음 피스 타입
                                                                                                                                                                                                                        sensor.AddObservation(board.GetNextPieceType());
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                /// <summary>
                                                                                                                                                                                                                                    /// AI 행동 처리 - 액션을 받아 게임에 적용
                                                                                                                                                                                                                                        /// </summary>
                                                                                                                                                                                                                                            public override void OnActionReceived(ActionBuffers actions)
                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                        int action = actions.DiscreteActions[0];

                                                                                                                                                                                                                                                                switch (action)
                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                    case 0: board.Move(Vector2Int.left);  break;  // 왼쪽 이동
                                                                                                                                                                                                                                                                                                case 1: board.Move(Vector2Int.right); break;  // 오른쪽 이동
                                                                                                                                                                                                                                                                                                            case 2: board.Rotate(1);              break;  // 시계방향 회전
                                                                                                                                                                                                                                                                                                                        case 3: board.Rotate(-1);             break;  // 반시계방향 회전
                                                                                                                                                                                                                                                                                                                                    case 4: board.HardDrop();             break;  // 하드드롭
                                                                                                                                                                                                                                                                                                                                                case 5: break;                                // 대기
                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                board.LockPiece();

                                                                                                                                                                                                                                                                                                                                                                        // 보상 계산
                                                                                                                                                                                                                                                                                                                                                                                float reward = board.GetStepReward();
                                                                                                                                                                                                                                                                                                                                                                                        AddReward(reward);

                                                                                                                                                                                                                                                                                                                                                                                                // 게임오버 체크
                                                                                                                                                                                                                                                                                                                                                                                                        if (board.IsGameOver())
                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                            AddReward(-1f);
                                                                                                                                                                                                                                                                                                                                                                                                                                        EndEpisode();
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        /// <summary>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            /// 사람이 직접 테스트할 때 사용 (Heuristic 모드)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                /// </summary>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public override void Heuristic(in ActionBuffers actionsOut)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var discreteActions = actionsOut.DiscreteActions;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        discreteActions[0] = 5; // 기본값: 대기

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (Input.GetKey(KeyCode.LeftArrow))  discreteActions[0] = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (Input.GetKey(KeyCode.RightArrow)) discreteActions[0] = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (Input.GetKey(KeyCode.UpArrow))    discreteActions[0] = 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (Input.GetKey(KeyCode.Z))          discreteActions[0] = 3;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (Input.GetKey(KeyCode.Space))      discreteActions[0] = 4;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }